name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você deseje monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ou a versão do Node.js que você estiver usando

      - name: Install dependencies
        run: npm ci  # Instala as dependências usando o npm ci

      - name: Build the project
        run: npm run build  # Executa o build do projeto React

      - name: Deploy to Vercel
        run: npx vercel --prod --yes  # Deploy para o ambiente de produção da Vercel
