name: Deploy to Vercel

on:
  push:
    branches:
      - main # Altere para o nome da branch desejada, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a versão necessária para o seu projeto

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm ci

      # Passo 4: Build do projeto
      - name: Build project
        run: npm run build

      # Passo 5: Deploy para o Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --yes
